return {
    add = {
        options = {
            ["--all"] = "--all",
            ["--chmod"] = "--chmod",
            ["--dry-run"] = "--dry-run",
            ["--edit"] = "--edit",
            ["--force"] = "--force",
            ["--ignore-errors"] = "--ignore-errors",
            ["--ignore-missing"] = "--ignore-missing",
            ["--ignore-removal"] = "--ignore-removal",
            ["--intent-to-add"] = "--intent-to-add",
            ["--interactive"] = "--interactive",
            ["--no-all"] = "--no-all",
            ["--patch"] = "--patch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--refresh"] = "--refresh",
            ["--renormalize"] = "--renormalize",
            ["--sparse"] = "--sparse",
            ["--update"] = "--update",
            ["--verbose"] = "--verbose",
        },
    },
    am = {
        options = {
            ["--3way"] = "--3way",
            ["--abort"] = "--abort",
            ["--allow-empty"] = "--allow-empty",
            ["--committer-date-is-author-date"] = "--committer-date-is-author-date",
            ["--continue"] = "--continue",
            ["--directory"] = "--directory",
            ["--empty"] = "--empty",
            ["--exclude"] = "--exclude",
            ["--gpg-sign"] = "--gpg-sign",
            ["--ignore-date"] = "--ignore-date",
            ["--ignore-space-change"] = "--ignore-space-change",
            ["--ignore-whitespace"] = "--ignore-whitespace",
            ["--include"] = "--include",
            ["--interactive"] = "--interactive",
            ["--keep"] = "--keep",
            ["--keep-cr"] = "--keep-cr",
            ["--keep-non-patch"] = "--keep-non-patch",
            ["--message-id"] = "--message-id",
            ["--no-keep-cr"] = "--no-keep-cr",
            ["--patch-format"] = "--patch-format",
            ["--quiet"] = "--quiet",
            ["--quit"] = "--quit",
            ["--quoted-cr"] = "--quoted-cr",
            ["--reject"] = "--reject",
            ["--rerere-autoupdate"] = "--rerere-autoupdate",
            ["--resolved"] = "--resolved",
            ["--resolvemsg"] = "--resolvemsg",
            ["--scissors"] = "--scissors",
            ["--show-current-patch"] = "--show-current-patch",
            ["--signoff"] = "--signoff",
            ["--skip"] = "--skip",
            ["--utf8"] = "--utf8",
            ["--whitespace"] = "--whitespace",
        },
    },
    annotate = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--color-by-age"] = "--color-by-age",
            ["--color-lines"] = "--color-lines",
            ["--contents"] = "--contents",
            ["--ignore-rev"] = "--ignore-rev",
            ["--ignore-revs-file"] = "--ignore-revs-file",
            ["--incremental"] = "--incremental",
            ["--line-porcelain"] = "--line-porcelain",
            ["--minimal"] = "--minimal",
            ["--porcelain"] = "--porcelain",
            ["--progress"] = "--progress",
            ["--root"] = "--root",
            ["--score-debug"] = "--score-debug",
            ["--show-email"] = "--show-email",
            ["--show-name"] = "--show-name",
            ["--show-number"] = "--show-number",
            ["--show-stats"] = "--show-stats",
        },
    },
    apply = {
        options = {
            ["--3way"] = "--3way",
            ["--allow-empty"] = "--allow-empty",
            ["--allow-overlap"] = "--allow-overlap",
            ["--apply"] = "--apply",
            ["--build-fake-ancestor"] = "--build-fake-ancestor",
            ["--cached"] = "--cached",
            ["--check"] = "--check",
            ["--directory"] = "--directory",
            ["--exclude"] = "--exclude",
            ["--ignore-space-change"] = "--ignore-space-change",
            ["--ignore-whitespace"] = "--ignore-whitespace",
            ["--inaccurate-eof"] = "--inaccurate-eof",
            ["--include"] = "--include",
            ["--index"] = "--index",
            ["--intent-to-add"] = "--intent-to-add",
            ["--no-add"] = "--no-add",
            ["--numstat"] = "--numstat",
            ["--quiet"] = "--quiet",
            ["--recount"] = "--recount",
            ["--reject"] = "--reject",
            ["--reverse"] = "--reverse",
            ["--stat"] = "--stat",
            ["--summary"] = "--summary",
            ["--unidiff-zero"] = "--unidiff-zero",
            ["--unsafe-paths"] = "--unsafe-paths",
            ["--verbose"] = "--verbose",
            ["--whitespace"] = "--whitespace",
        },
    },
    archimport = {
        options = {},
    },
    archive = {
        options = {
            ["--add-file"] = "--add-file",
            ["--add-virtual-file"] = "--add-virtual-file",
            ["--exec"] = "--exec",
            ["--format"] = "--format",
            ["--list"] = "--list",
            ["--output"] = "--output",
            ["--prefix"] = "--prefix",
            ["--remote"] = "--remote",
            ["--verbose"] = "--verbose",
            ["--worktree-attributes"] = "--worktree-attributes",
        },
    },
    bisect = {
        options = {
            ["--first-parent"] = "--first-parent",
            ["--no-checkout"] = "--no-checkout",
            ["--term-"] = "--term-",
            ["--term-bad"] = "--term-bad",
            ["--term-good"] = "--term-good",
        },
    },
    blame = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--color-by-age"] = "--color-by-age",
            ["--color-lines"] = "--color-lines",
            ["--contents"] = "--contents",
            ["--ignore-rev"] = "--ignore-rev",
            ["--ignore-revs-file"] = "--ignore-revs-file",
            ["--incremental"] = "--incremental",
            ["--line-porcelain"] = "--line-porcelain",
            ["--minimal"] = "--minimal",
            ["--porcelain"] = "--porcelain",
            ["--progress"] = "--progress",
            ["--root"] = "--root",
            ["--score-debug"] = "--score-debug",
            ["--show-email"] = "--show-email",
            ["--show-name"] = "--show-name",
            ["--show-number"] = "--show-number",
            ["--show-stats"] = "--show-stats",
        },
    },
    branch = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--all"] = "--all",
            ["--color"] = "--color",
            ["--column"] = "--column",
            ["--contains"] = "--contains",
            ["--copy"] = "--copy",
            ["--create-reflog"] = "--create-reflog",
            ["--delete"] = "--delete",
            ["--edit-description"] = "--edit-description",
            ["--force"] = "--force",
            ["--format"] = "--format",
            ["--ignore-case"] = "--ignore-case",
            ["--list"] = "--list",
            ["--merged"] = "--merged",
            ["--move"] = "--move",
            ["--no-contains"] = "--no-contains",
            ["--no-merged"] = "--no-merged",
            ["--points-at"] = "--points-at",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--remotes"] = "--remotes",
            ["--set-upstream-to"] = "--set-upstream-to",
            ["--show-current"] = "--show-current",
            ["--sort"] = "--sort",
            ["--track"] = "--track",
            ["--unset-upstream"] = "--unset-upstream",
            ["--verbose"] = "--verbose",
        },
    },
    bugreport = {
        options = {
            ["--diagnose"] = "--diagnose",
            ["--output-directory"] = "--output-directory",
            ["--suffix"] = "--suffix",
        },
    },
    bundle = {
        options = {
            ["--all-progress"] = "--all-progress",
            ["--all-progress-implied"] = "--all-progress-implied",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--version"] = "--version",
        },
    },
    ["cat-file"] = {
        options = {
            ["--allow-unknown-type"] = "--allow-unknown-type",
            ["--batch"] = "--batch",
            ["--batch-all-objects"] = "--batch-all-objects",
            ["--batch-check"] = "--batch-check",
            ["--batch-command"] = "--batch-command",
            ["--buffer"] = "--buffer",
            ["--filters"] = "--filters",
            ["--follow-symlinks"] = "--follow-symlinks",
            ["--mailmap"] = "--mailmap",
            ["--path"] = "--path",
            ["--textconv"] = "--textconv",
            ["--unordered"] = "--unordered",
            ["--use-mailmap"] = "--use-mailmap",
        },
    },
    ["check-attr"] = {
        options = {
            ["--all"] = "--all",
            ["--cached"] = "--cached",
            ["--stdin"] = "--stdin",
        },
    },
    ["check-ignore"] = {
        options = {
            ["--no-index"] = "--no-index",
            ["--non-matching"] = "--non-matching",
            ["--quiet"] = "--quiet",
            ["--stdin"] = "--stdin",
            ["--verbose"] = "--verbose",
        },
    },
    ["check-mailmap"] = {
        options = {
            ["--stdin"] = "--stdin",
        },
    },
    ["check-ref-format"] = {
        options = {
            ["--branch"] = "--branch",
            ["--normalize"] = "--normalize",
        },
    },
    checkout = {
        options = {
            ["--conflict"] = "--conflict",
            ["--detach"] = "--detach",
            ["--force"] = "--force",
            ["--guess"] = "--guess",
            ["--ignore-other-worktrees"] = "--ignore-other-worktrees",
            ["--ignore-skip-worktree-bits"] = "--ignore-skip-worktree-bits",
            ["--merge"] = "--merge",
            ["--orphan"] = "--orphan",
            ["--ours"] = "--ours",
            ["--overlay"] = "--overlay",
            ["--overwrite-ignore"] = "--overwrite-ignore",
            ["--patch"] = "--patch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--theirs"] = "--theirs",
            ["--track"] = "--track",
        },
    },
    ["checkout-index"] = {
        options = {
            ["--all"] = "--all",
            ["--force"] = "--force",
            ["--ignore-skip-worktree-bits"] = "--ignore-skip-worktree-bits",
            ["--index"] = "--index",
            ["--no-create"] = "--no-create",
            ["--prefix"] = "--prefix",
            ["--quiet"] = "--quiet",
            ["--stage"] = "--stage",
            ["--stdin"] = "--stdin",
            ["--temp"] = "--temp",
        },
    },
    cherry = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--verbose"] = "--verbose",
        },
    },
    ["cherry-pick"] = {
        options = {
            ["--abort"] = "--abort",
            ["--allow-empty"] = "--allow-empty",
            ["--allow-empty-message"] = "--allow-empty-message",
            ["--cleanup"] = "--cleanup",
            ["--continue"] = "--continue",
            ["--edit"] = "--edit",
            ["--ff"] = "--ff",
            ["--gpg-sign"] = "--gpg-sign",
            ["--keep-redundant-commits"] = "--keep-redundant-commits",
            ["--mainline"] = "--mainline",
            ["--no-commit"] = "--no-commit",
            ["--quit"] = "--quit",
            ["--rerere-autoupdate"] = "--rerere-autoupdate",
            ["--signoff"] = "--signoff",
            ["--skip"] = "--skip",
            ["--strategy"] = "--strategy",
            ["--strategy-option"] = "--strategy-option",
        },
    },
    clean = {
        options = {
            ["--dry-run"] = "--dry-run",
            ["--exclude"] = "--exclude",
            ["--force"] = "--force",
            ["--interactive"] = "--interactive",
            ["--quiet"] = "--quiet",
        },
    },
    clone = {
        options = {
            ["--also-filter-submodules"] = "--also-filter-submodules",
            ["--bare"] = "--bare",
            ["--branch"] = "--branch",
            ["--bundle-uri"] = "--bundle-uri",
            ["--config"] = "--config",
            ["--depth"] = "--depth",
            ["--dissociate"] = "--dissociate",
            ["--filter"] = "--filter",
            ["--ipv4"] = "--ipv4",
            ["--ipv6"] = "--ipv6",
            ["--jobs"] = "--jobs",
            ["--local"] = "--local",
            ["--mirror"] = "--mirror",
            ["--no-checkout"] = "--no-checkout",
            ["--no-hardlinks"] = "--no-hardlinks",
            ["--no-tags"] = "--no-tags",
            ["--origin"] = "--origin",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--recursive"] = "--recursive",
            ["--reference"] = "--reference",
            ["--reference-if-able"] = "--reference-if-able",
            ["--reject-shallow"] = "--reject-shallow",
            ["--remote-submodules"] = "--remote-submodules",
            ["--separate-git-dir"] = "--separate-git-dir",
            ["--server-option"] = "--server-option",
            ["--shallow-exclude"] = "--shallow-exclude",
            ["--shallow-since"] = "--shallow-since",
            ["--shallow-submodules"] = "--shallow-submodules",
            ["--shared"] = "--shared",
            ["--single-branch"] = "--single-branch",
            ["--sparse"] = "--sparse",
            ["--template"] = "--template",
            ["--upload-pack"] = "--upload-pack",
            ["--verbose"] = "--verbose",
        },
    },
    column = {
        options = {
            ["--command"] = "--command",
            ["--indent"] = "--indent",
            ["--mode"] = "--mode",
            ["--nl"] = "--nl",
            ["--padding"] = "--padding",
            ["--raw-mode"] = "--raw-mode",
            ["--width"] = "--width",
        },
    },
    commit = {
        options = {
            ["--ahead-behind"] = "--ahead-behind",
            ["--all"] = "--all",
            ["--allow-empty"] = "--allow-empty",
            ["--allow-empty-message"] = "--allow-empty-message",
            ["--amend"] = "--amend",
            ["--author"] = "--author",
            ["--branch"] = "--branch",
            ["--cleanup"] = "--cleanup",
            ["--date"] = "--date",
            ["--dry-run"] = "--dry-run",
            ["--edit"] = "--edit",
            ["--file"] = "--file",
            ["--fixup"] = "--fixup",
            ["--gpg-sign"] = "--gpg-sign",
            ["--include"] = "--include",
            ["--interactive"] = "--interactive",
            ["--long"] = "--long",
            ["--message"] = "--message",
            ["--no-post-rewrite"] = "--no-post-rewrite",
            ["--no-verify"] = "--no-verify",
            ["--null"] = "--null",
            ["--only"] = "--only",
            ["--patch"] = "--patch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--porcelain"] = "--porcelain",
            ["--quiet"] = "--quiet",
            ["--reedit-message"] = "--reedit-message",
            ["--reset-author"] = "--reset-author",
            ["--reuse-message"] = "--reuse-message",
            ["--short"] = "--short",
            ["--signoff"] = "--signoff",
            ["--squash"] = "--squash",
            ["--status"] = "--status",
            ["--template"] = "--template",
            ["--trailer"] = "--trailer",
            ["--untracked-files"] = "--untracked-files",
            ["--verbose"] = "--verbose",
        },
    },
    ["commit-graph"] = {
        options = {
            ["--append"] = "--append",
            ["--changed-paths"] = "--changed-paths",
            ["--object-dir"] = "--object-dir",
            ["--reachable"] = "--reachable",
            ["--shallow"] = "--shallow",
            ["--split"] = "--split",
            ["--stdin-commits"] = "--stdin-commits",
            ["--stdin-packs"] = "--stdin-packs",
        },
    },
    ["commit-tree"] = {
        options = {
            ["--gpg-sign"] = "--gpg-sign",
        },
    },
    config = {
        options = {
            ["--add"] = "--add",
            ["--blob"] = "--blob",
            ["--bool"] = "--bool",
            ["--bool-or-int"] = "--bool-or-int",
            ["--bool-or-str"] = "--bool-or-str",
            ["--default"] = "--default",
            ["--edit"] = "--edit",
            ["--expiry-date"] = "--expiry-date",
            ["--file"] = "--file",
            ["--fixed-value"] = "--fixed-value",
            ["--get"] = "--get",
            ["--get-all"] = "--get-all",
            ["--get-color"] = "--get-color",
            ["--get-colorbool"] = "--get-colorbool",
            ["--get-regexp"] = "--get-regexp",
            ["--get-urlmatch"] = "--get-urlmatch",
            ["--global"] = "--global",
            ["--includes"] = "--includes",
            ["--int"] = "--int",
            ["--list"] = "--list",
            ["--local"] = "--local",
            ["--name-only"] = "--name-only",
            ["--null"] = "--null",
            ["--path"] = "--path",
            ["--remove-section"] = "--remove-section",
            ["--rename-section"] = "--rename-section",
            ["--replace-all"] = "--replace-all",
            ["--show-origin"] = "--show-origin",
            ["--show-scope"] = "--show-scope",
            ["--system"] = "--system",
            ["--type"] = "--type",
            ["--unset"] = "--unset",
            ["--unset-all"] = "--unset-all",
            ["--worktree"] = "--worktree",
        },
    },
    ["count-objects"] = {
        options = {
            ["--human-readable"] = "--human-readable",
            ["--verbose"] = "--verbose",
        },
    },
    credential = {
        options = {},
    },
    ["credential-cache"] = {
        options = {
            ["--socket"] = "--socket",
            ["--timeout"] = "--timeout",
        },
    },
    ["credential-netrc"] = {
        options = {
            ["--compilation"] = "--compilation",
        },
    },
    ["credential-osxkeychain"] = {
        options = {},
    },
    ["credential-store"] = {
        options = {
            ["--file"] = "--file",
        },
    },
    cvsexportcommit = {
        options = {},
    },
    cvsimport = {
        options = {},
    },
    cvsserver = {
        options = {},
    },
    daemon = {
        options = {
            ["--access-hook"] = "--access-hook",
            ["--base-path"] = "--base-path",
            ["--base-path-relaxed"] = "--base-path-relaxed",
            ["--detach"] = "--detach",
            ["--export-all"] = "--export-all",
            ["--group"] = "--group",
            ["--inetd"] = "--inetd",
            ["--init-timeout"] = "--init-timeout",
            ["--interpolated-path"] = "--interpolated-path",
            ["--listen"] = "--listen",
            ["--log-destination"] = "--log-destination",
            ["--max-connections"] = "--max-connections",
            ["--pid-file"] = "--pid-file",
            ["--port"] = "--port",
            ["--reuseaddr"] = "--reuseaddr",
            ["--strict-paths"] = "--strict-paths",
            ["--syslog"] = "--syslog",
            ["--timeout"] = "--timeout",
            ["--user"] = "--user",
            ["--user-path"] = "--user-path",
            ["--verbose"] = "--verbose",
        },
    },
    describe = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--all"] = "--all",
            ["--always"] = "--always",
            ["--broken"] = "--broken",
            ["--candidates"] = "--candidates",
            ["--contains"] = "--contains",
            ["--debug"] = "--debug",
            ["--dirty"] = "--dirty",
            ["--exact-match"] = "--exact-match",
            ["--exclude"] = "--exclude",
            ["--first-parent"] = "--first-parent",
            ["--long"] = "--long",
            ["--match"] = "--match",
            ["--tags"] = "--tags",
        },
    },
    diagnose = {
        options = {
            ["--mode"] = "--mode",
            ["--output-directory"] = "--output-directory",
            ["--suffix"] = "--suffix",
        },
    },
    diff = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--cached"] = "--cached",
            ["--find-copies-harder"] = "--find-copies-harder",
            ["--full-index"] = "--full-index",
            ["--merge-base"] = "--merge-base",
            ["--name-only"] = "--name-only",
            ["--name-status"] = "--name-status",
            ["--no-index"] = "--no-index",
            ["--numstat"] = "--numstat",
            ["--patch-with-raw"] = "--patch-with-raw",
            ["--patch-with-stat"] = "--patch-with-stat",
            ["--pickaxe-all"] = "--pickaxe-all",
            ["--stat"] = "--stat",
            ["--text"] = "--text",
        },
    },
    ["diff-files"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--cc"] = "--cc",
            ["--find-copies-harder"] = "--find-copies-harder",
            ["--full-index"] = "--full-index",
            ["--name-only"] = "--name-only",
            ["--name-status"] = "--name-status",
            ["--numstat"] = "--numstat",
            ["--patch-with-raw"] = "--patch-with-raw",
            ["--patch-with-stat"] = "--patch-with-stat",
            ["--pickaxe-all"] = "--pickaxe-all",
            ["--stat"] = "--stat",
            ["--text"] = "--text",
        },
    },
    ["diff-index"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--cached"] = "--cached",
            ["--find-copies-harder"] = "--find-copies-harder",
            ["--full-index"] = "--full-index",
            ["--merge-base"] = "--merge-base",
            ["--name-only"] = "--name-only",
            ["--name-status"] = "--name-status",
            ["--numstat"] = "--numstat",
            ["--patch-with-raw"] = "--patch-with-raw",
            ["--patch-with-stat"] = "--patch-with-stat",
            ["--pickaxe-all"] = "--pickaxe-all",
            ["--stat"] = "--stat",
            ["--text"] = "--text",
        },
    },
    ["diff-tree"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--cc"] = "--cc",
            ["--combined-all-paths"] = "--combined-all-paths",
            ["--find-copies-harder"] = "--find-copies-harder",
            ["--full-index"] = "--full-index",
            ["--merge-base"] = "--merge-base",
            ["--name-only"] = "--name-only",
            ["--name-status"] = "--name-status",
            ["--no-commit-id"] = "--no-commit-id",
            ["--numstat"] = "--numstat",
            ["--patch-with-raw"] = "--patch-with-raw",
            ["--patch-with-stat"] = "--patch-with-stat",
            ["--pickaxe-all"] = "--pickaxe-all",
            ["--pretty"] = "--pretty",
            ["--root"] = "--root",
            ["--stat"] = "--stat",
            ["--stdin"] = "--stdin",
            ["--text"] = "--text",
        },
    },
    difftool = {
        options = {
            ["--dir-diff"] = "--dir-diff",
            ["--extcmd"] = "--extcmd",
            ["--gui"] = "--gui",
            ["--no-index"] = "--no-index",
            ["--no-prompt"] = "--no-prompt",
            ["--symlinks"] = "--symlinks",
            ["--tool"] = "--tool",
            ["--tool-help"] = "--tool-help",
            ["--trust-exit-code"] = "--trust-exit-code",
        },
    },
    ["fast-export"] = {
        options = {
            ["--anonymize"] = "--anonymize",
            ["--anonymize-map"] = "--anonymize-map",
            ["--export-marks"] = "--export-marks",
            ["--fake-missing-tagger"] = "--fake-missing-tagger",
            ["--full-tree"] = "--full-tree",
            ["--import-marks"] = "--import-marks",
            ["--import-marks-if-exists"] = "--import-marks-if-exists",
            ["--mark-tags"] = "--mark-tags",
            ["--no-data"] = "--no-data",
            ["--progress"] = "--progress",
            ["--reencode"] = "--reencode",
            ["--reference-excluded-parents"] = "--reference-excluded-parents",
            ["--refspec"] = "--refspec",
            ["--show-original-ids"] = "--show-original-ids",
            ["--signed-tags"] = "--signed-tags",
            ["--tag-of-filtered-object"] = "--tag-of-filtered-object",
            ["--use-done-feature"] = "--use-done-feature",
        },
    },
    ["fast-import"] = {
        options = {
            ["--active-branches"] = "--active-branches",
            ["--big-file-threshold"] = "--big-file-threshold",
            ["--date-format"] = "--date-format",
            ["--depth"] = "--depth",
            ["--export-marks"] = "--export-marks",
            ["--max-pack-size"] = "--max-pack-size",
        },
    },
    fetch = {
        options = {
            ["--all"] = "--all",
            ["--append"] = "--append",
            ["--atomic"] = "--atomic",
            ["--auto"] = "--auto",
            ["--auto-gc"] = "--auto-gc",
            ["--auto-maintenance"] = "--auto-maintenance",
            ["--deepen"] = "--deepen",
            ["--depth"] = "--depth",
            ["--dry-run"] = "--dry-run",
            ["--filter"] = "--filter",
            ["--force"] = "--force",
            ["--ipv4"] = "--ipv4",
            ["--ipv6"] = "--ipv6",
            ["--jobs"] = "--jobs",
            ["--keep"] = "--keep",
            ["--multiple"] = "--multiple",
            ["--negotiate-only"] = "--negotiate-only",
            ["--negotiation-tip"] = "--negotiation-tip",
            ["--no-tags"] = "--no-tags",
            ["--prefetch"] = "--prefetch",
            ["--progress"] = "--progress",
            ["--prune"] = "--prune",
            ["--prune-tags"] = "--prune-tags",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--refetch"] = "--refetch",
            ["--refmap"] = "--refmap",
            ["--server-option"] = "--server-option",
            ["--set-upstream"] = "--set-upstream",
            ["--shallow-exclude"] = "--shallow-exclude",
            ["--shallow-since"] = "--shallow-since",
            ["--show-forced-updates"] = "--show-forced-updates",
            ["--stdin"] = "--stdin",
            ["--tags"] = "--tags",
            ["--unshallow"] = "--unshallow",
            ["--update-head-ok"] = "--update-head-ok",
            ["--update-shallow"] = "--update-shallow",
            ["--upload-pack"] = "--upload-pack",
            ["--verbose"] = "--verbose",
            ["--write-commit-graph"] = "--write-commit-graph",
            ["--write-fetch-head"] = "--write-fetch-head",
        },
    },
    ["fetch-pack"] = {
        options = {
            ["--all"] = "--all",
            ["--depth"] = "--depth",
            ["--diag-url"] = "--diag-url",
            ["--include-tag"] = "--include-tag",
            ["--keep"] = "--keep",
            ["--no-progress"] = "--no-progress",
            ["--quiet"] = "--quiet",
            ["--stdin"] = "--stdin",
            ["--thin"] = "--thin",
            ["--upload-pack"] = "--upload-pack",
        },
    },
    ["filter-branch"] = {
        options = {
            ["--commit-filter"] = "--commit-filter",
            ["--env-filter"] = "--env-filter",
            ["--force"] = "--force",
            ["--index-filter"] = "--index-filter",
            ["--msg-filter"] = "--msg-filter",
            ["--original"] = "--original",
            ["--parent-filter"] = "--parent-filter",
            ["--setup"] = "--setup",
            ["--state-branch"] = "--state-branch",
            ["--subdirectory-filter"] = "--subdirectory-filter",
            ["--tag-name-filter"] = "--tag-name-filter",
            ["--tree-filter"] = "--tree-filter",
        },
    },
    ["fmt-merge-msg"] = {
        options = {
            ["--file"] = "--file",
            ["--into-name"] = "--into-name",
            ["--log"] = "--log",
            ["--message"] = "--message",
            ["--no-log"] = "--no-log",
        },
    },
    ["for-each-ref"] = {
        options = {
            ["--color"] = "--color",
            ["--contains"] = "--contains",
            ["--count"] = "--count",
            ["--format"] = "--format",
            ["--ignore-case"] = "--ignore-case",
            ["--merged"] = "--merged",
            ["--no-contains"] = "--no-contains",
            ["--no-merged"] = "--no-merged",
            ["--perl"] = "--perl",
            ["--points-at"] = "--points-at",
            ["--python"] = "--python",
            ["--shell"] = "--shell",
            ["--sort"] = "--sort",
            ["--tcl"] = "--tcl",
        },
    },
    ["for-each-repo"] = {
        options = {
            ["--config"] = "--config",
        },
    },
    ["format-patch"] = {
        options = {
            ["--add-header"] = "--add-header",
            ["--attach"] = "--attach",
            ["--base"] = "--base",
            ["--cc"] = "--cc",
            ["--cover-from-description"] = "--cover-from-description",
            ["--cover-letter"] = "--cover-letter",
            ["--creation-factor"] = "--creation-factor",
            ["--filename-max-length"] = "--filename-max-length",
            ["--force-in-body-from"] = "--force-in-body-from",
            ["--from"] = "--from",
            ["--ignore-if-in-upstream"] = "--ignore-if-in-upstream",
            ["--in-reply-to"] = "--in-reply-to",
            ["--inline"] = "--inline",
            ["--interdiff"] = "--interdiff",
            ["--keep-subject"] = "--keep-subject",
            ["--no-binary"] = "--no-binary",
            ["--no-numbered"] = "--no-numbered",
            ["--no-stat"] = "--no-stat",
            ["--numbered"] = "--numbered",
            ["--numbered-files"] = "--numbered-files",
            ["--output-directory"] = "--output-directory",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--range-diff"] = "--range-diff",
            ["--reroll-count"] = "--reroll-count",
            ["--rfc"] = "--rfc",
            ["--signature"] = "--signature",
            ["--signature-file"] = "--signature-file",
            ["--signoff"] = "--signoff",
            ["--start-number"] = "--start-number",
            ["--stdout"] = "--stdout",
            ["--subject-prefix"] = "--subject-prefix",
            ["--suffix"] = "--suffix",
            ["--thread"] = "--thread",
            ["--to"] = "--to",
            ["--zero-commit"] = "--zero-commit",
        },
    },
    fsck = {
        options = {
            ["--cache"] = "--cache",
            ["--connectivity-only"] = "--connectivity-only",
            ["--dangling"] = "--dangling",
            ["--full"] = "--full",
            ["--lost-found"] = "--lost-found",
            ["--name-objects"] = "--name-objects",
            ["--no-reflogs"] = "--no-reflogs",
            ["--progress"] = "--progress",
            ["--reflogs"] = "--reflogs",
            ["--root"] = "--root",
            ["--strict"] = "--strict",
            ["--tags"] = "--tags",
            ["--unreachable"] = "--unreachable",
            ["--verbose"] = "--verbose",
        },
    },
    ["fsck-objects"] = {
        options = {
            ["--cache"] = "--cache",
            ["--connectivity-only"] = "--connectivity-only",
            ["--dangling"] = "--dangling",
            ["--full"] = "--full",
            ["--lost-found"] = "--lost-found",
            ["--name-objects"] = "--name-objects",
            ["--no-reflogs"] = "--no-reflogs",
            ["--progress"] = "--progress",
            ["--reflogs"] = "--reflogs",
            ["--root"] = "--root",
            ["--strict"] = "--strict",
            ["--tags"] = "--tags",
            ["--unreachable"] = "--unreachable",
            ["--verbose"] = "--verbose",
        },
    },
    gc = {
        options = {
            ["--aggressive"] = "--aggressive",
            ["--auto"] = "--auto",
            ["--cruft"] = "--cruft",
            ["--force"] = "--force",
            ["--keep-largest-pack"] = "--keep-largest-pack",
            ["--prune"] = "--prune",
            ["--quiet"] = "--quiet",
        },
    },
    ["get-tar-commit-id"] = {
        options = {},
    },
    grep = {
        options = {
            ["--after-context"] = "--after-context",
            ["--all-match"] = "--all-match",
            ["--and"] = "--and",
            ["--basic-regexp"] = "--basic-regexp",
            ["--before-context"] = "--before-context",
            ["--break"] = "--break",
            ["--cached"] = "--cached",
            ["--color"] = "--color",
            ["--column"] = "--column",
            ["--context"] = "--context",
            ["--count"] = "--count",
            ["--exclude-standard"] = "--exclude-standard",
            ["--ext-grep"] = "--ext-grep",
            ["--extended-regexp"] = "--extended-regexp",
            ["--files-with-matches"] = "--files-with-matches",
            ["--files-without-match"] = "--files-without-match",
            ["--fixed-strings"] = "--fixed-strings",
            ["--full-name"] = "--full-name",
            ["--function-context"] = "--function-context",
            ["--heading"] = "--heading",
            ["--ignore-case"] = "--ignore-case",
            ["--invert-match"] = "--invert-match",
            ["--line-number"] = "--line-number",
            ["--max-count"] = "--max-count",
            ["--max-depth"] = "--max-depth",
            ["--name-only"] = "--name-only",
            ["--no-index"] = "--no-index",
            ["--not"] = "--not",
            ["--null"] = "--null",
            ["--only-matching"] = "--only-matching",
            ["--open-files-in-pager"] = "--open-files-in-pager",
            ["--or"] = "--or",
            ["--perl-regexp"] = "--perl-regexp",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--recursive"] = "--recursive",
            ["--show-function"] = "--show-function",
            ["--text"] = "--text",
            ["--textconv"] = "--textconv",
            ["--threads"] = "--threads",
            ["--untracked"] = "--untracked",
            ["--word-regexp"] = "--word-regexp",
        },
    },
    ["hash-object"] = {
        options = {
            ["--literally"] = "--literally",
            ["--no-filters"] = "--no-filters",
            ["--path"] = "--path",
            ["--stdin"] = "--stdin",
            ["--stdin-paths"] = "--stdin-paths",
        },
    },
    help = {
        options = {
            ["--aliases"] = "--aliases",
            ["--all"] = "--all",
            ["--config"] = "--config",
            ["--developer-interfaces"] = "--developer-interfaces",
            ["--external-commands"] = "--external-commands",
            ["--guides"] = "--guides",
            ["--info"] = "--info",
            ["--man"] = "--man",
            ["--user-interfaces"] = "--user-interfaces",
            ["--verbose"] = "--verbose",
            ["--web"] = "--web",
        },
    },
    hook = {
        options = {
            ["--ignore-missing"] = "--ignore-missing",
        },
    },
    ["http-backend"] = {
        options = {},
    },
    ["http-fetch"] = {
        options = {
            ["--packfile"] = "--packfile",
            ["--recover"] = "--recover",
            ["--stdin"] = "--stdin",
        },
    },
    ["http-push"] = {
        options = {
            ["--all"] = "--all",
            ["--dry-run"] = "--dry-run",
            ["--force"] = "--force",
            ["--verbose"] = "--verbose",
        },
    },
    ["imap-send"] = {
        options = {
            ["--curl"] = "--curl",
            ["--quiet"] = "--quiet",
            ["--verbose"] = "--verbose",
        },
    },
    ["index-pack"] = {
        options = {
            ["--fix-thin"] = "--fix-thin",
            ["--keep"] = "--keep",
            ["--stdin"] = "--stdin",
            ["--strict"] = "--strict",
            ["--verify"] = "--verify",
        },
    },
    init = {
        options = {
            ["--bare"] = "--bare",
            ["--initial-branch"] = "--initial-branch",
            ["--object-format"] = "--object-format",
            ["--quiet"] = "--quiet",
            ["--separate-git-dir"] = "--separate-git-dir",
            ["--shared"] = "--shared",
            ["--template"] = "--template",
        },
    },
    ["init-db"] = {
        options = {
            ["--bare"] = "--bare",
            ["--initial-branch"] = "--initial-branch",
            ["--object-format"] = "--object-format",
            ["--quiet"] = "--quiet",
            ["--separate-git-dir"] = "--separate-git-dir",
            ["--shared"] = "--shared",
            ["--template"] = "--template",
        },
    },
    instaweb = {
        options = {
            ["--browser"] = "--browser",
            ["--httpd"] = "--httpd",
            ["--local"] = "--local",
            ["--module-path"] = "--module-path",
            ["--port"] = "--port",
            ["--restart"] = "--restart",
            ["--start"] = "--start",
            ["--stop"] = "--stop",
        },
    },
    ["interpret-trailers"] = {
        options = {
            ["---"] = "---",
            ["--if-exists"] = "--if-exists",
            ["--if-missing"] = "--if-missing",
            ["--in-place"] = "--in-place",
            ["--no-divider"] = "--no-divider",
            ["--only-input"] = "--only-input",
            ["--only-trailers"] = "--only-trailers",
            ["--parse"] = "--parse",
            ["--trailer"] = "--trailer",
            ["--trim-empty"] = "--trim-empty",
            ["--unfold"] = "--unfold",
            ["--where"] = "--where",
        },
    },
    log = {
        options = {
            ["--clear-decorations"] = "--clear-decorations",
            ["--decorate"] = "--decorate",
            ["--decorate-refs"] = "--decorate-refs",
            ["--decorate-refs-exclude"] = "--decorate-refs-exclude",
            ["--mailmap"] = "--mailmap",
            ["--quiet"] = "--quiet",
            ["--source"] = "--source",
            ["--use-mailmap"] = "--use-mailmap",
        },
    },
    ["ls-files"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--cached"] = "--cached",
            ["--debug"] = "--debug",
            ["--deduplicate"] = "--deduplicate",
            ["--deleted"] = "--deleted",
            ["--directory"] = "--directory",
            ["--empty-directory"] = "--empty-directory",
            ["--eol"] = "--eol",
            ["--error-unmatch"] = "--error-unmatch",
            ["--exclude"] = "--exclude",
            ["--exclude-from"] = "--exclude-from",
            ["--exclude-per-directory"] = "--exclude-per-directory",
            ["--exclude-standard"] = "--exclude-standard",
            ["--format"] = "--format",
            ["--full-name"] = "--full-name",
            ["--ignored"] = "--ignored",
            ["--killed"] = "--killed",
            ["--modified"] = "--modified",
            ["--others"] = "--others",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--resolve-undo"] = "--resolve-undo",
            ["--sparse"] = "--sparse",
            ["--stage"] = "--stage",
            ["--unmerged"] = "--unmerged",
            ["--with-tree"] = "--with-tree",
        },
    },
    ["ls-remote"] = {
        options = {
            ["--exit-code"] = "--exit-code",
            ["--get-url"] = "--get-url",
            ["--heads"] = "--heads",
            ["--quiet"] = "--quiet",
            ["--refs"] = "--refs",
            ["--server-option"] = "--server-option",
            ["--sort"] = "--sort",
            ["--symref"] = "--symref",
            ["--tags"] = "--tags",
            ["--upload-pack"] = "--upload-pack",
        },
    },
    ["ls-tree"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--format"] = "--format",
            ["--full-name"] = "--full-name",
            ["--full-tree"] = "--full-tree",
            ["--long"] = "--long",
            ["--name-only"] = "--name-only",
            ["--name-status"] = "--name-status",
            ["--object-only"] = "--object-only",
        },
    },
    mailinfo = {
        options = {
            ["--encoding"] = "--encoding",
            ["--message-id"] = "--message-id",
            ["--quoted-cr"] = "--quoted-cr",
            ["--scissors"] = "--scissors",
        },
    },
    mailsplit = {
        options = {
            ["--keep-cr"] = "--keep-cr",
        },
    },
    maintenance = {
        options = {},
    },
    merge = {
        options = {
            ["--abort"] = "--abort",
            ["--allow-unrelated-histories"] = "--allow-unrelated-histories",
            ["--autostash"] = "--autostash",
            ["--cleanup"] = "--cleanup",
            ["--commit"] = "--commit",
            ["--continue"] = "--continue",
            ["--edit"] = "--edit",
            ["--ff"] = "--ff",
            ["--ff-only"] = "--ff-only",
            ["--file"] = "--file",
            ["--gpg-sign"] = "--gpg-sign",
            ["--into-name"] = "--into-name",
            ["--log"] = "--log",
            ["--message"] = "--message",
            ["--no-verify"] = "--no-verify",
            ["--overwrite-ignore"] = "--overwrite-ignore",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--quit"] = "--quit",
            ["--rerere-autoupdate"] = "--rerere-autoupdate",
            ["--signoff"] = "--signoff",
            ["--squash"] = "--squash",
            ["--stat"] = "--stat",
            ["--strategy"] = "--strategy",
            ["--strategy-option"] = "--strategy-option",
            ["--summary"] = "--summary",
            ["--verbose"] = "--verbose",
            ["--verify-signatures"] = "--verify-signatures",
        },
    },
    ["merge-base"] = {
        options = {
            ["--all"] = "--all",
            ["--fork-point"] = "--fork-point",
            ["--independent"] = "--independent",
            ["--is-ancestor"] = "--is-ancestor",
            ["--octopus"] = "--octopus",
        },
    },
    ["merge-file"] = {
        options = {
            ["--diff3"] = "--diff3",
            ["--marker-size"] = "--marker-size",
            ["--ours"] = "--ours",
            ["--quiet"] = "--quiet",
            ["--stdout"] = "--stdout",
            ["--theirs"] = "--theirs",
            ["--union"] = "--union",
            ["--zdiff3"] = "--zdiff3",
        },
    },
    ["merge-index"] = {
        options = {},
    },
    ["merge-octopus"] = {
        options = {},
    },
    ["merge-one-file"] = {
        options = {},
    },
    ["merge-ours"] = {
        options = {},
    },
    ["merge-recursive"] = {
        options = {},
    },
    ["merge-recursive-ours"] = {
        options = {},
    },
    ["merge-recursive-theirs"] = {
        options = {},
    },
    ["merge-resolve"] = {
        options = {},
    },
    ["merge-subtree"] = {
        options = {},
    },
    ["merge-tree"] = {
        options = {
            ["--allow-unrelated-histories"] = "--allow-unrelated-histories",
            ["--messages"] = "--messages",
            ["--name-only"] = "--name-only",
            ["--stdin"] = "--stdin",
            ["--trivial-merge"] = "--trivial-merge",
            ["--write-tree"] = "--write-tree",
        },
    },
    mergetool = {
        options = {
            ["--gui"] = "--gui",
            ["--no-gui"] = "--no-gui",
            ["--no-prompt"] = "--no-prompt",
            ["--prompt"] = "--prompt",
            ["--tool"] = "--tool",
            ["--tool-help"] = "--tool-help",
        },
    },
    mktag = {
        options = {
            ["--strict"] = "--strict",
        },
    },
    mktree = {
        options = {
            ["--batch"] = "--batch",
            ["--missing"] = "--missing",
        },
    },
    ["multi-pack-index"] = {
        options = {
            ["--batch-size"] = "--batch-size",
            ["--object-dir"] = "--object-dir",
            ["--preferred-pack"] = "--preferred-pack",
            ["--refs-snapshot"] = "--refs-snapshot",
        },
    },
    mv = {
        options = {
            ["--dry-run"] = "--dry-run",
            ["--force"] = "--force",
            ["--sparse"] = "--sparse",
            ["--verbose"] = "--verbose",
        },
    },
    ["name-rev"] = {
        options = {
            ["--all"] = "--all",
            ["--always"] = "--always",
            ["--annotate-stdin"] = "--annotate-stdin",
            ["--exclude"] = "--exclude",
            ["--name-only"] = "--name-only",
            ["--refs"] = "--refs",
            ["--stdin"] = "--stdin",
            ["--tags"] = "--tags",
            ["--undefined"] = "--undefined",
        },
    },
    notes = {
        options = {
            ["--abort"] = "--abort",
            ["--allow-empty"] = "--allow-empty",
            ["--commit"] = "--commit",
            ["--ref"] = "--ref",
        },
    },
    p4 = {
        options = {},
    },
    ["pack-objects"] = {
        options = {
            ["--all"] = "--all",
            ["--all-progress"] = "--all-progress",
            ["--all-progress-implied"] = "--all-progress-implied",
            ["--compression"] = "--compression",
            ["--cruft"] = "--cruft",
            ["--cruft-expiration"] = "--cruft-expiration",
            ["--delta-base-offset"] = "--delta-base-offset",
            ["--delta-islands"] = "--delta-islands",
            ["--depth"] = "--depth",
            ["--exclude-promisor-objects"] = "--exclude-promisor-objects",
            ["--filter"] = "--filter",
            ["--honor-pack-keep"] = "--honor-pack-keep",
            ["--include-tag"] = "--include-tag",
            ["--incremental"] = "--incremental",
            ["--index-version"] = "--index-version",
            ["--indexed-objects"] = "--indexed-objects",
            ["--keep-pack"] = "--keep-pack",
            ["--keep-true-parents"] = "--keep-true-parents",
            ["--keep-unreachable"] = "--keep-unreachable",
            ["--local"] = "--local",
            ["--max-pack-size"] = "--max-pack-size",
            ["--missing"] = "--missing",
            ["--non-empty"] = "--non-empty",
            ["--pack-loose-unreachable"] = "--pack-loose-unreachable",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--reflog"] = "--reflog",
            ["--reuse-delta"] = "--reuse-delta",
            ["--reuse-object"] = "--reuse-object",
            ["--revs"] = "--revs",
            ["--shallow"] = "--shallow",
            ["--sparse"] = "--sparse",
            ["--stdin-packs"] = "--stdin-packs",
            ["--stdout"] = "--stdout",
            ["--thin"] = "--thin",
            ["--threads"] = "--threads",
            ["--unpack-unreachable"] = "--unpack-unreachable",
            ["--unpacked"] = "--unpacked",
            ["--uri-protocol"] = "--uri-protocol",
            ["--use-bitmap-index"] = "--use-bitmap-index",
            ["--window"] = "--window",
            ["--window-memory"] = "--window-memory",
            ["--write-bitmap-index"] = "--write-bitmap-index",
        },
    },
    ["pack-redundant"] = {
        options = {
            ["--all"] = "--all",
            ["--alt-odb"] = "--alt-odb",
            ["--verbose"] = "--verbose",
        },
    },
    ["pack-refs"] = {
        options = {
            ["--all"] = "--all",
            ["--no-prune"] = "--no-prune",
            ["--prune"] = "--prune",
        },
    },
    ["patch-id"] = {
        options = {
            ["--stable"] = "--stable",
            ["--unstable"] = "--unstable",
            ["--verbatim"] = "--verbatim",
        },
    },
    pickaxe = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--color-by-age"] = "--color-by-age",
            ["--color-lines"] = "--color-lines",
            ["--contents"] = "--contents",
            ["--ignore-rev"] = "--ignore-rev",
            ["--ignore-revs-file"] = "--ignore-revs-file",
            ["--incremental"] = "--incremental",
            ["--line-porcelain"] = "--line-porcelain",
            ["--minimal"] = "--minimal",
            ["--porcelain"] = "--porcelain",
            ["--progress"] = "--progress",
            ["--root"] = "--root",
            ["--score-debug"] = "--score-debug",
            ["--show-email"] = "--show-email",
            ["--show-name"] = "--show-name",
            ["--show-number"] = "--show-number",
            ["--show-stats"] = "--show-stats",
        },
    },
    prune = {
        options = {
            ["--dry-run"] = "--dry-run",
            ["--exclude-promisor-objects"] = "--exclude-promisor-objects",
            ["--expire"] = "--expire",
            ["--progress"] = "--progress",
            ["--verbose"] = "--verbose",
        },
    },
    ["prune-packed"] = {
        options = {
            ["--dry-run"] = "--dry-run",
            ["--quiet"] = "--quiet",
        },
    },
    pull = {
        options = {
            ["--all"] = "--all",
            ["--allow-unrelated-histories"] = "--allow-unrelated-histories",
            ["--append"] = "--append",
            ["--autostash"] = "--autostash",
            ["--cleanup"] = "--cleanup",
            ["--commit"] = "--commit",
            ["--deepen"] = "--deepen",
            ["--depth"] = "--depth",
            ["--dry-run"] = "--dry-run",
            ["--edit"] = "--edit",
            ["--ff"] = "--ff",
            ["--ff-only"] = "--ff-only",
            ["--force"] = "--force",
            ["--gpg-sign"] = "--gpg-sign",
            ["--ipv4"] = "--ipv4",
            ["--ipv6"] = "--ipv6",
            ["--jobs"] = "--jobs",
            ["--keep"] = "--keep",
            ["--log"] = "--log",
            ["--negotiation-tip"] = "--negotiation-tip",
            ["--progress"] = "--progress",
            ["--prune"] = "--prune",
            ["--quiet"] = "--quiet",
            ["--rebase"] = "--rebase",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--refmap"] = "--refmap",
            ["--server-option"] = "--server-option",
            ["--set-upstream"] = "--set-upstream",
            ["--shallow-exclude"] = "--shallow-exclude",
            ["--shallow-since"] = "--shallow-since",
            ["--show-forced-updates"] = "--show-forced-updates",
            ["--signoff"] = "--signoff",
            ["--squash"] = "--squash",
            ["--stat"] = "--stat",
            ["--strategy"] = "--strategy",
            ["--strategy-option"] = "--strategy-option",
            ["--tags"] = "--tags",
            ["--unshallow"] = "--unshallow",
            ["--update-shallow"] = "--update-shallow",
            ["--upload-pack"] = "--upload-pack",
            ["--verbose"] = "--verbose",
            ["--verify"] = "--verify",
            ["--verify-signatures"] = "--verify-signatures",
        },
    },
    push = {
        options = {
            ["--all"] = "--all",
            ["--atomic"] = "--atomic",
            ["--delete"] = "--delete",
            ["--dry-run"] = "--dry-run",
            ["--exec"] = "--exec",
            ["--follow-tags"] = "--follow-tags",
            ["--force"] = "--force",
            ["--force-if-includes"] = "--force-if-includes",
            ["--force-with-lease"] = "--force-with-lease",
            ["--ipv4"] = "--ipv4",
            ["--ipv6"] = "--ipv6",
            ["--mirror"] = "--mirror",
            ["--no-verify"] = "--no-verify",
            ["--porcelain"] = "--porcelain",
            ["--progress"] = "--progress",
            ["--prune"] = "--prune",
            ["--push-option"] = "--push-option",
            ["--quiet"] = "--quiet",
            ["--receive-pack"] = "--receive-pack",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--repo"] = "--repo",
            ["--set-upstream"] = "--set-upstream",
            ["--signed"] = "--signed",
            ["--tags"] = "--tags",
            ["--thin"] = "--thin",
            ["--verbose"] = "--verbose",
        },
    },
    quiltimport = {
        options = {
            ["--author"] = "--author",
            ["--dry-run"] = "--dry-run",
            ["--keep-non-patch"] = "--keep-non-patch",
            ["--patches"] = "--patches",
            ["--series"] = "--series",
        },
    },
    ["range-diff"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--anchored"] = "--anchored",
            ["--binary"] = "--binary",
            ["--break-rewrites"] = "--break-rewrites",
            ["--check"] = "--check",
            ["--color"] = "--color",
            ["--color-moved"] = "--color-moved",
            ["--color-moved-ws"] = "--color-moved-ws",
            ["--color-words"] = "--color-words",
            ["--compact-summary"] = "--compact-summary",
            ["--creation-factor"] = "--creation-factor",
            ["--cumulative"] = "--cumulative",
            ["--diff-algorithm"] = "--diff-algorithm",
            ["--diff-filter"] = "--diff-filter",
            ["--dirstat"] = "--dirstat",
            ["--dirstat-by-file"] = "--dirstat-by-file",
            ["--dst-prefix"] = "--dst-prefix",
            ["--exit-code"] = "--exit-code",
            ["--ext-diff"] = "--ext-diff",
            ["--find-copies"] = "--find-copies",
            ["--find-copies-harder"] = "--find-copies-harder",
            ["--find-object"] = "--find-object",
            ["--find-renames"] = "--find-renames",
            ["--follow"] = "--follow",
            ["--full-index"] = "--full-index",
            ["--function-context"] = "--function-context",
            ["--histogram"] = "--histogram",
            ["--ignore-all-space"] = "--ignore-all-space",
            ["--ignore-blank-lines"] = "--ignore-blank-lines",
            ["--ignore-cr-at-eol"] = "--ignore-cr-at-eol",
            ["--ignore-matching-lines"] = "--ignore-matching-lines",
            ["--ignore-space-at-eol"] = "--ignore-space-at-eol",
            ["--ignore-space-change"] = "--ignore-space-change",
            ["--ignore-submodules"] = "--ignore-submodules",
            ["--indent-heuristic"] = "--indent-heuristic",
            ["--inter-hunk-context"] = "--inter-hunk-context",
            ["--irreversible-delete"] = "--irreversible-delete",
            ["--ita-invisible-in-index"] = "--ita-invisible-in-index",
            ["--ita-visible-in-index"] = "--ita-visible-in-index",
            ["--left-only"] = "--left-only",
            ["--line-prefix"] = "--line-prefix",
            ["--minimal"] = "--minimal",
            ["--name-only"] = "--name-only",
            ["--name-status"] = "--name-status",
            ["--no-dual-color"] = "--no-dual-color",
            ["--no-patch"] = "--no-patch",
            ["--no-prefix"] = "--no-prefix",
            ["--no-renames"] = "--no-renames",
            ["--notes"] = "--notes",
            ["--numstat"] = "--numstat",
            ["--output"] = "--output",
            ["--output-indicator-context"] = "--output-indicator-context",
            ["--output-indicator-new"] = "--output-indicator-new",
            ["--output-indicator-old"] = "--output-indicator-old",
            ["--patch"] = "--patch",
            ["--patch-with-raw"] = "--patch-with-raw",
            ["--patch-with-stat"] = "--patch-with-stat",
            ["--patience"] = "--patience",
            ["--pickaxe-all"] = "--pickaxe-all",
            ["--pickaxe-regex"] = "--pickaxe-regex",
            ["--quiet"] = "--quiet",
            ["--raw"] = "--raw",
            ["--relative"] = "--relative",
            ["--rename-empty"] = "--rename-empty",
            ["--right-only"] = "--right-only",
            ["--rotate-to"] = "--rotate-to",
            ["--shortstat"] = "--shortstat",
            ["--skip-to"] = "--skip-to",
            ["--src-prefix"] = "--src-prefix",
            ["--stat"] = "--stat",
            ["--stat-count"] = "--stat-count",
            ["--stat-graph-width"] = "--stat-graph-width",
            ["--stat-name-width"] = "--stat-name-width",
            ["--stat-width"] = "--stat-width",
            ["--submodule"] = "--submodule",
            ["--summary"] = "--summary",
            ["--text"] = "--text",
            ["--textconv"] = "--textconv",
            ["--unified"] = "--unified",
            ["--word-diff"] = "--word-diff",
            ["--word-diff-regex"] = "--word-diff-regex",
            ["--ws-error-highlight"] = "--ws-error-highlight",
        },
    },
    ["read-tree"] = {
        options = {
            ["--aggressive"] = "--aggressive",
            ["--debug-unpack"] = "--debug-unpack",
            ["--dry-run"] = "--dry-run",
            ["--empty"] = "--empty",
            ["--exclude-per-directory"] = "--exclude-per-directory",
            ["--index-output"] = "--index-output",
            ["--no-sparse-checkout"] = "--no-sparse-checkout",
            ["--prefix"] = "--prefix",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--reset"] = "--reset",
            ["--trivial"] = "--trivial",
            ["--verbose"] = "--verbose",
        },
    },
    rebase = {
        options = {
            ["--abort"] = "--abort",
            ["--apply"] = "--apply",
            ["--autosquash"] = "--autosquash",
            ["--autostash"] = "--autostash",
            ["--committer-date-is-author-date"] = "--committer-date-is-author-date",
            ["--continue"] = "--continue",
            ["--edit-todo"] = "--edit-todo",
            ["--empty"] = "--empty",
            ["--exec"] = "--exec",
            ["--force-rebase"] = "--force-rebase",
            ["--fork-point"] = "--fork-point",
            ["--gpg-sign"] = "--gpg-sign",
            ["--ignore-whitespace"] = "--ignore-whitespace",
            ["--interactive"] = "--interactive",
            ["--keep-base"] = "--keep-base",
            ["--merge"] = "--merge",
            ["--no-ff"] = "--no-ff",
            ["--no-stat"] = "--no-stat",
            ["--no-verify"] = "--no-verify",
            ["--onto"] = "--onto",
            ["--quiet"] = "--quiet",
            ["--quit"] = "--quit",
            ["--reapply-cherry-picks"] = "--reapply-cherry-picks",
            ["--rebase-merges"] = "--rebase-merges",
            ["--rerere-autoupdate"] = "--rerere-autoupdate",
            ["--reschedule-failed-exec"] = "--reschedule-failed-exec",
            ["--reset-author-date"] = "--reset-author-date",
            ["--root"] = "--root",
            ["--show-current-patch"] = "--show-current-patch",
            ["--signoff"] = "--signoff",
            ["--skip"] = "--skip",
            ["--strategy"] = "--strategy",
            ["--strategy-option"] = "--strategy-option",
            ["--update-refs"] = "--update-refs",
            ["--verbose"] = "--verbose",
            ["--whitespace"] = "--whitespace",
        },
    },
    ["receive-pack"] = {
        options = {
            ["--quiet"] = "--quiet",
        },
    },
    reflog = {
        options = {
            ["--all"] = "--all",
            ["--dry-run"] = "--dry-run",
            ["--expire"] = "--expire",
            ["--expire-unreachable"] = "--expire-unreachable",
            ["--rewrite"] = "--rewrite",
            ["--single-worktree"] = "--single-worktree",
            ["--stale-fix"] = "--stale-fix",
            ["--updateref"] = "--updateref",
            ["--verbose"] = "--verbose",
        },
    },
    remote = {
        options = {
            ["--add"] = "--add",
            ["--all"] = "--all",
            ["--auto"] = "--auto",
            ["--delete"] = "--delete",
            ["--dry-run"] = "--dry-run",
            ["--mirror"] = "--mirror",
            ["--no-tags"] = "--no-tags",
            ["--prune"] = "--prune",
            ["--push"] = "--push",
            ["--tags"] = "--tags",
            ["--verbose"] = "--verbose",
        },
    },
    ["remote-ext"] = {
        options = {},
    },
    ["remote-fd"] = {
        options = {},
    },
    ["remote-ftp"] = {
        options = {},
    },
    ["remote-ftps"] = {
        options = {},
    },
    ["remote-http"] = {
        options = {},
    },
    ["remote-https"] = {
        options = {},
    },
    repack = {
        options = {
            ["--cruft"] = "--cruft",
            ["--cruft-expiration"] = "--cruft-expiration",
            ["--delta-islands"] = "--delta-islands",
            ["--depth"] = "--depth",
            ["--expire-to"] = "--expire-to",
            ["--geometric"] = "--geometric",
            ["--keep-pack"] = "--keep-pack",
            ["--keep-unreachable"] = "--keep-unreachable",
            ["--local"] = "--local",
            ["--max-pack-size"] = "--max-pack-size",
            ["--no-reuse-delta"] = "--no-reuse-delta",
            ["--no-reuse-object"] = "--no-reuse-object",
            ["--pack-kept-objects"] = "--pack-kept-objects",
            ["--quiet"] = "--quiet",
            ["--threads"] = "--threads",
            ["--unpack-unreachable"] = "--unpack-unreachable",
            ["--window"] = "--window",
            ["--window-memory"] = "--window-memory",
            ["--write-bitmap-index"] = "--write-bitmap-index",
            ["--write-midx"] = "--write-midx",
        },
    },
    replace = {
        options = {
            ["--convert-graft-file"] = "--convert-graft-file",
            ["--delete"] = "--delete",
            ["--edit"] = "--edit",
            ["--force"] = "--force",
            ["--format"] = "--format",
            ["--graft"] = "--graft",
            ["--list"] = "--list",
            ["--raw"] = "--raw",
        },
    },
    ["request-pull"] = {
        options = {},
    },
    rerere = {
        options = {
            ["--rerere-autoupdate"] = "--rerere-autoupdate",
        },
    },
    reset = {
        options = {
            ["--hard"] = "--hard",
            ["--intent-to-add"] = "--intent-to-add",
            ["--keep"] = "--keep",
            ["--merge"] = "--merge",
            ["--mixed"] = "--mixed",
            ["--no-refresh"] = "--no-refresh",
            ["--patch"] = "--patch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--soft"] = "--soft",
        },
    },
    restore = {
        options = {
            ["--conflict"] = "--conflict",
            ["--ignore-skip-worktree-bits"] = "--ignore-skip-worktree-bits",
            ["--ignore-unmerged"] = "--ignore-unmerged",
            ["--merge"] = "--merge",
            ["--ours"] = "--ours",
            ["--overlay"] = "--overlay",
            ["--patch"] = "--patch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--source"] = "--source",
            ["--staged"] = "--staged",
            ["--theirs"] = "--theirs",
            ["--worktree"] = "--worktree",
        },
    },
    ["rev-list"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--abbrev-commit"] = "--abbrev-commit",
            ["--all"] = "--all",
            ["--bisect"] = "--bisect",
            ["--bisect-all"] = "--bisect-all",
            ["--bisect-vars"] = "--bisect-vars",
            ["--branches"] = "--branches",
            ["--children"] = "--children",
            ["--count"] = "--count",
            ["--date-order"] = "--date-order",
            ["--disk-usage"] = "--disk-usage",
            ["--exclude-hidden"] = "--exclude-hidden",
            ["--header"] = "--header",
            ["--left-right"] = "--left-right",
            ["--max-age"] = "--max-age",
            ["--max-count"] = "--max-count",
            ["--max-parents"] = "--max-parents",
            ["--min-age"] = "--min-age",
            ["--min-parents"] = "--min-parents",
            ["--no-abbrev"] = "--no-abbrev",
            ["--no-max-parents"] = "--no-max-parents",
            ["--no-merges"] = "--no-merges",
            ["--no-min-parents"] = "--no-min-parents",
            ["--objects"] = "--objects",
            ["--objects-edge"] = "--objects-edge",
            ["--parents"] = "--parents",
            ["--pretty"] = "--pretty",
            ["--quiet"] = "--quiet",
            ["--remotes"] = "--remotes",
            ["--remove-empty"] = "--remove-empty",
            ["--reverse"] = "--reverse",
            ["--sparse"] = "--sparse",
            ["--stdin"] = "--stdin",
            ["--tags"] = "--tags",
            ["--topo-order"] = "--topo-order",
            ["--unpacked"] = "--unpacked",
        },
    },
    ["rev-parse"] = {
        options = {
            ["--parseopt"] = "--parseopt",
            ["--sq-quote"] = "--sq-quote",
        },
    },
    revert = {
        options = {
            ["--abort"] = "--abort",
            ["--cleanup"] = "--cleanup",
            ["--continue"] = "--continue",
            ["--edit"] = "--edit",
            ["--gpg-sign"] = "--gpg-sign",
            ["--mainline"] = "--mainline",
            ["--no-commit"] = "--no-commit",
            ["--quit"] = "--quit",
            ["--reference"] = "--reference",
            ["--rerere-autoupdate"] = "--rerere-autoupdate",
            ["--signoff"] = "--signoff",
            ["--skip"] = "--skip",
            ["--strategy"] = "--strategy",
            ["--strategy-option"] = "--strategy-option",
        },
    },
    rm = {
        options = {
            ["--cached"] = "--cached",
            ["--dry-run"] = "--dry-run",
            ["--force"] = "--force",
            ["--ignore-unmatch"] = "--ignore-unmatch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--quiet"] = "--quiet",
            ["--sparse"] = "--sparse",
        },
    },
    ["send-email"] = {
        options = {
            ["--8bit-encoding"] = "--8bit-encoding",
            ["--batch-size"] = "--batch-size",
            ["--cc-cmd"] = "--cc-cmd",
            ["--compose"] = "--compose",
            ["--compose-encoding"] = "--compose-encoding",
            ["--confirm"] = "--confirm",
            ["--dry-run"] = "--dry-run",
            ["--dump-aliases"] = "--dump-aliases",
            ["--envelope-sender"] = "--envelope-sender",
            ["--force"] = "--force",
            ["--from"] = "--from",
            ["--identity"] = "--identity",
            ["--in-reply-to"] = "--in-reply-to",
            ["--no-smtp-auth"] = "--no-smtp-auth",
            ["--quiet"] = "--quiet",
            ["--relogin-delay"] = "--relogin-delay",
            ["--reply-to"] = "--reply-to",
            ["--sendmail-cmd"] = "--sendmail-cmd",
            ["--smtp-auth"] = "--smtp-auth",
            ["--smtp-debug"] = "--smtp-debug",
            ["--smtp-domain"] = "--smtp-domain",
            ["--smtp-encryption"] = "--smtp-encryption",
            ["--smtp-pass"] = "--smtp-pass",
            ["--smtp-server"] = "--smtp-server",
            ["--smtp-server-option"] = "--smtp-server-option",
            ["--smtp-server-port"] = "--smtp-server-port",
            ["--smtp-ssl"] = "--smtp-ssl",
            ["--smtp-ssl-cert-path"] = "--smtp-ssl-cert-path",
            ["--smtp-user"] = "--smtp-user",
            ["--subject"] = "--subject",
            ["--suppress-cc"] = "--suppress-cc",
            ["--to-cmd"] = "--to-cmd",
            ["--transfer-encoding"] = "--transfer-encoding",
        },
    },
    ["send-pack"] = {
        options = {
            ["--all"] = "--all",
            ["--atomic"] = "--atomic",
            ["--dry-run"] = "--dry-run",
            ["--exec"] = "--exec",
            ["--force"] = "--force",
            ["--force-if-includes"] = "--force-if-includes",
            ["--force-with-lease"] = "--force-with-lease",
            ["--helper-status"] = "--helper-status",
            ["--mirror"] = "--mirror",
            ["--progress"] = "--progress",
            ["--push-option"] = "--push-option",
            ["--quiet"] = "--quiet",
            ["--receive-pack"] = "--receive-pack",
            ["--remote"] = "--remote",
            ["--signed"] = "--signed",
            ["--stateless-rpc"] = "--stateless-rpc",
            ["--stdin"] = "--stdin",
            ["--thin"] = "--thin",
            ["--verbose"] = "--verbose",
        },
    },
    shell = {
        options = {},
    },
    shortlog = {
        options = {
            ["--committer"] = "--committer",
            ["--email"] = "--email",
            ["--group"] = "--group",
            ["--numbered"] = "--numbered",
            ["--pretty"] = "--pretty",
            ["--summary"] = "--summary",
        },
    },
    show = {
        options = {
            ["--clear-decorations"] = "--clear-decorations",
            ["--decorate"] = "--decorate",
            ["--decorate-refs"] = "--decorate-refs",
            ["--decorate-refs-exclude"] = "--decorate-refs-exclude",
            ["--mailmap"] = "--mailmap",
            ["--quiet"] = "--quiet",
            ["--source"] = "--source",
            ["--use-mailmap"] = "--use-mailmap",
        },
    },
    ["show-branch"] = {
        options = {
            ["--all"] = "--all",
            ["--color"] = "--color",
            ["--current"] = "--current",
            ["--date-order"] = "--date-order",
            ["--independent"] = "--independent",
            ["--list"] = "--list",
            ["--merge-base"] = "--merge-base",
            ["--more"] = "--more",
            ["--no-color"] = "--no-color",
            ["--no-name"] = "--no-name",
            ["--reflog"] = "--reflog",
            ["--remotes"] = "--remotes",
            ["--sha1-name"] = "--sha1-name",
            ["--sparse"] = "--sparse",
            ["--topics"] = "--topics",
            ["--topo-order"] = "--topo-order",
        },
    },
    ["show-index"] = {
        options = {
            ["--object-format"] = "--object-format",
        },
    },
    ["show-ref"] = {
        options = {
            ["--abbrev"] = "--abbrev",
            ["--dereference"] = "--dereference",
            ["--exclude-existing"] = "--exclude-existing",
            ["--hash"] = "--hash",
            ["--head"] = "--head",
            ["--heads"] = "--heads",
            ["--quiet"] = "--quiet",
            ["--tags"] = "--tags",
            ["--verify"] = "--verify",
        },
    },
    ["sparse-checkout"] = {
        options = {},
    },
    stage = {
        options = {
            ["--all"] = "--all",
            ["--chmod"] = "--chmod",
            ["--dry-run"] = "--dry-run",
            ["--edit"] = "--edit",
            ["--force"] = "--force",
            ["--ignore-errors"] = "--ignore-errors",
            ["--ignore-missing"] = "--ignore-missing",
            ["--ignore-removal"] = "--ignore-removal",
            ["--intent-to-add"] = "--intent-to-add",
            ["--interactive"] = "--interactive",
            ["--no-all"] = "--no-all",
            ["--patch"] = "--patch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--refresh"] = "--refresh",
            ["--renormalize"] = "--renormalize",
            ["--sparse"] = "--sparse",
            ["--update"] = "--update",
            ["--verbose"] = "--verbose",
        },
    },
    stash = {
        options = {
            ["--all"] = "--all",
            ["--include-untracked"] = "--include-untracked",
            ["--index"] = "--index",
            ["--message"] = "--message",
            ["--only-untracked"] = "--only-untracked",
            ["--patch"] = "--patch",
            ["--pathspec-file-nul"] = "--pathspec-file-nul",
            ["--pathspec-from-file"] = "--pathspec-from-file",
            ["--quiet"] = "--quiet",
            ["--staged"] = "--staged",
        },
    },
    status = {
        options = {
            ["--ahead-behind"] = "--ahead-behind",
            ["--branch"] = "--branch",
            ["--column"] = "--column",
            ["--find-renames"] = "--find-renames",
            ["--ignore-submodules"] = "--ignore-submodules",
            ["--ignored"] = "--ignored",
            ["--long"] = "--long",
            ["--no-renames"] = "--no-renames",
            ["--null"] = "--null",
            ["--porcelain"] = "--porcelain",
            ["--short"] = "--short",
            ["--show-stash"] = "--show-stash",
            ["--untracked-files"] = "--untracked-files",
            ["--verbose"] = "--verbose",
        },
    },
    stripspace = {
        options = {
            ["--comment-lines"] = "--comment-lines",
            ["--strip-comments"] = "--strip-comments",
        },
    },
    submodule = {
        options = {
            ["--all"] = "--all",
            ["--branch"] = "--branch",
            ["--cached"] = "--cached",
            ["--checkout"] = "--checkout",
            ["--default"] = "--default",
            ["--files"] = "--files",
            ["--filter"] = "--filter",
            ["--force"] = "--force",
            ["--init"] = "--init",
            ["--merge"] = "--merge",
            ["--name"] = "--name",
            ["--no-fetch"] = "--no-fetch",
            ["--quiet"] = "--quiet",
            ["--rebase"] = "--rebase",
            ["--recursive"] = "--recursive",
            ["--reference"] = "--reference",
            ["--remote"] = "--remote",
            ["--summary-limit"] = "--summary-limit",
        },
    },
    subtree = {
        options = {
            ["--annotate"] = "--annotate",
            ["--branch"] = "--branch",
            ["--help"] = "--help",
            ["--ignore-joins"] = "--ignore-joins",
            ["--message"] = "--message",
            ["--onto"] = "--onto",
            ["--prefix"] = "--prefix",
            ["--rejoin"] = "--rejoin",
            ["--squash"] = "--squash",
        },
    },
    switch = {
        options = {
            ["--conflict"] = "--conflict",
            ["--create"] = "--create",
            ["--detach"] = "--detach",
            ["--discard-changes"] = "--discard-changes",
            ["--force"] = "--force",
            ["--force-create"] = "--force-create",
            ["--guess"] = "--guess",
            ["--ignore-other-worktrees"] = "--ignore-other-worktrees",
            ["--merge"] = "--merge",
            ["--orphan"] = "--orphan",
            ["--overwrite-ignore"] = "--overwrite-ignore",
            ["--progress"] = "--progress",
            ["--quiet"] = "--quiet",
            ["--recurse-submodules"] = "--recurse-submodules",
            ["--track"] = "--track",
        },
    },
    ["symbolic-ref"] = {
        options = {
            ["--delete"] = "--delete",
            ["--no-recurse"] = "--no-recurse",
            ["--quiet"] = "--quiet",
            ["--recurse"] = "--recurse",
            ["--short"] = "--short",
        },
    },
    tag = {
        options = {
            ["--annotate"] = "--annotate",
            ["--cleanup"] = "--cleanup",
            ["--color"] = "--color",
            ["--column"] = "--column",
            ["--contains"] = "--contains",
            ["--create-reflog"] = "--create-reflog",
            ["--delete"] = "--delete",
            ["--edit"] = "--edit",
            ["--file"] = "--file",
            ["--force"] = "--force",
            ["--format"] = "--format",
            ["--ignore-case"] = "--ignore-case",
            ["--list"] = "--list",
            ["--local-user"] = "--local-user",
            ["--merged"] = "--merged",
            ["--message"] = "--message",
            ["--no-column"] = "--no-column",
            ["--no-contains"] = "--no-contains",
            ["--no-merged"] = "--no-merged",
            ["--points-at"] = "--points-at",
            ["--sign"] = "--sign",
            ["--sort"] = "--sort",
            ["--verify"] = "--verify",
        },
    },
    ["unpack-file"] = {
        options = {},
    },
    ["unpack-objects"] = {
        options = {
            ["--strict"] = "--strict",
        },
    },
    ["update-index"] = {
        options = {
            ["--add"] = "--add",
            ["--again"] = "--again",
            ["--assume-unchanged"] = "--assume-unchanged",
            ["--cacheinfo"] = "--cacheinfo",
            ["--chmod"] = "--chmod",
            ["--clear-resolve-undo"] = "--clear-resolve-undo",
            ["--force-remove"] = "--force-remove",
            ["--force-untracked-cache"] = "--force-untracked-cache",
            ["--force-write-index"] = "--force-write-index",
            ["--fsmonitor"] = "--fsmonitor",
            ["--fsmonitor-valid"] = "--fsmonitor-valid",
            ["--ignore-missing"] = "--ignore-missing",
            ["--ignore-skip-worktree-entries"] = "--ignore-skip-worktree-entries",
            ["--ignore-submodules"] = "--ignore-submodules",
            ["--index-info"] = "--index-info",
            ["--index-version"] = "--index-version",
            ["--info-only"] = "--info-only",
            ["--no-assume-unchanged"] = "--no-assume-unchanged",
            ["--no-fsmonitor-valid"] = "--no-fsmonitor-valid",
            ["--no-skip-worktree"] = "--no-skip-worktree",
            ["--really-refresh"] = "--really-refresh",
            ["--refresh"] = "--refresh",
            ["--remove"] = "--remove",
            ["--replace"] = "--replace",
            ["--skip-worktree"] = "--skip-worktree",
            ["--split-index"] = "--split-index",
            ["--stdin"] = "--stdin",
            ["--test-untracked-cache"] = "--test-untracked-cache",
            ["--unmerged"] = "--unmerged",
            ["--unresolve"] = "--unresolve",
            ["--untracked-cache"] = "--untracked-cache",
            ["--verbose"] = "--verbose",
        },
    },
    ["update-ref"] = {
        options = {
            ["--create-reflog"] = "--create-reflog",
            ["--no-deref"] = "--no-deref",
            ["--stdin"] = "--stdin",
        },
    },
    ["update-server-info"] = {
        options = {
            ["--force"] = "--force",
        },
    },
    ["upload-archive"] = {
        options = {},
    },
    ["upload-pack"] = {
        options = {
            ["--advertise-refs"] = "--advertise-refs",
            ["--stateless-rpc"] = "--stateless-rpc",
            ["--strict"] = "--strict",
            ["--timeout"] = "--timeout",
        },
    },
    var = {
        options = {},
    },
    ["verify-commit"] = {
        options = {
            ["--raw"] = "--raw",
            ["--verbose"] = "--verbose",
        },
    },
    ["verify-pack"] = {
        options = {
            ["--object-format"] = "--object-format",
            ["--stat-only"] = "--stat-only",
            ["--verbose"] = "--verbose",
        },
    },
    ["verify-tag"] = {
        options = {
            ["--format"] = "--format",
            ["--raw"] = "--raw",
            ["--verbose"] = "--verbose",
        },
    },
    version = {
        options = {
            ["--build-options"] = "--build-options",
        },
    },
    whatchanged = {
        options = {
            ["--clear-decorations"] = "--clear-decorations",
            ["--decorate"] = "--decorate",
            ["--decorate-refs"] = "--decorate-refs",
            ["--decorate-refs-exclude"] = "--decorate-refs-exclude",
            ["--mailmap"] = "--mailmap",
            ["--quiet"] = "--quiet",
            ["--source"] = "--source",
            ["--use-mailmap"] = "--use-mailmap",
        },
    },
    worktree = {
        options = {
            ["--checkout"] = "--checkout",
            ["--detach"] = "--detach",
            ["--expire"] = "--expire",
            ["--lock"] = "--lock",
            ["--porcelain"] = "--porcelain",
            ["--reason"] = "--reason",
        },
    },
    ["write-tree"] = {
        options = {
            ["--missing-ok"] = "--missing-ok",
            ["--prefix"] = "--prefix",
        },
    },
}
