local M = {}

---@alias DisplayStrategy "print" | "ui" | "show" | "diff" | "blame" | "mergetool" | "terminal"
M.DISPLAY_STRATEGIES = {
    UI = "ui",
    SHOW = "show",
    DIFF = "diff",
    BLAME = "blame",
    MERGETOOL = "mergetool",
    TERMINAL = "terminal",
}

M.PORCELAIN_COMMANDS = {
    "add",
    "am",
    "annotate",
    "archimport",
    "archive",
    "bisect",
    "blame",
    "branch",
    "bundle",
    "checkout",
    "cherry",
    "cherry-pick",
    "citool",
    "clean",
    "clone",
    "commit",
    "config",
    "count-objects",
    "cvsexportcommit",
    "cvsimport",
    "cvsserver",
    "describe",
    "diff",
    "difftool",
    "fast-export",
    "fast-import",
    "fetch",
    "filter-branch",
    "format-patch",
    "fsck",
    "gc",
    "get-tar-commit-id",
    "grep",
    "gui",
    "help",
    "imap-send",
    "init",
    "instaweb",
    "log",
    "merge",
    "merge-tree",
    "mergetool",
    "mv",
    "notes",
    "p4",
    "pack-refs",
    "prune",
    "pull",
    "push",
    "quiltimport",
    "rebase",
    "reflog",
    "relink",
    "remote",
    "repack",
    "replace",
    "request-pull",
    "rerere",
    "reset",
    "rev-parse",
    "revert",
    "rm",
    "send-email",
    "shortlog",
    "show",
    "show-branch",
    "stash",
    "status",
    "submodule",
    "svn",
    "tag",
    "verify-commit",
    "verify-tag",
    "whatchanged",
    "worktree",
}

M.BASE_COMMANDS = {
    "add",
    "bisect",
    "blame",
    "branch",
    "checkout",
    "cherry-pick",
    "clean",
    "clone",
    "commit",
    "diff",
    "difftool",
    "fetch",
    "gc",
    "grep",
    "help",
    "init",
    "log",
    "merge",
    "mergetool",
    "mv",
    "pull",
    "push",
    "rebase",
    "reflog",
    "remote",
    "reset",
    "revert",
    "rm",
    "show",
    "stash",
    "status",
    "switch",
    "tag",
    "worktree",
}

M.SUBCOMMAND_FLAGS = {
    add = { "-A" },
    rebase = { "--interactive", "-i" },
    reset = {},
    revert = {},
    difftool = {},
    bisect = {},
    rm = {},
    branch = {},
    show = {},
    help = {},
    checkout = {},
    stash = {},
    ["cherry-pick"] = {},
    status = {},
    clean = {},
    tag = {},
    clone = {},
    worktree = {},
    commit = {
        "-a",
        "-p",
        "-C",
        "-c",
        "-F",
        "-m",
        "-t",
        "-e",
        "-s",
        "-S",
        "-n",
        "--amend",
        "--dry-run",
        "--fixup",
        "--squash",
        "--reset-author",
        "--short",
        "--branch",
        "--porcelain",
        "--long",
        "--null",
        "--file",
        "--author",
        "--date",
        "--no-verify",
        "--allow-empty",
        "--allow-empty-message",
        "--cleanup",
        "--status",
        "--no-status",
        "--gpg-sign",
        "--help",
        "--reuse-message",
    },
    diff = {},
    fetch = {},
    gc = {},
    mergetool = {},
    grep = {},
    init = {},
    reflog = {},
    log = {},
    merge = {},
    remote = {},
    mv = {},
    pull = {},
    push = {},
    blame = {},
}

return M
