name: panvimdoc

on: [push]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: alien # Output vimdoc project name (required)
          # The following are all optional
          pandoc: "README.md" # Input pandoc file
          version: "NVIM v0.11.0" # Vim version number
          treesitter: true # Use treesitter for highlighting codeblocks
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
